name: snapsnap
description: SnapSnap FronEnd Project
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0


environment:
  sdk: '>=3.0.1 <4.0.0'
dependencies:
  image_picker: ^0.8.4+4
  camera: ^0.9.4
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shimmer: ^3.0.0
  flutter_slidable: ^0.6.0
  dio: ^5.2.1
  provider: ^6.0.5
  flutter_secure_storage: ^8.0.0
  carousel_slider: ^4.2.1
  flutter_storage_path: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

